version: "3.7"
services:
  mongodb:
    image : mongo:latest
    container_name: mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
    - mongodb:/data/db
    ports:
    - 27019:27017
    restart: unless-stopped

volumes:
  mongodb:
    driver: local
